import Head from 'next/head'
import { Inter } from 'next/font/google'
import customButton from '@/components/customButton'
import Link from 'next/link'
import Image from 'next/image'
import { HiOutlineArrowNarrowRight } from "react-icons/hi"
import Searchbar from '@/components/Searchbar'





const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Attendr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='  bg-white px-10 md:px-20 lg:px-40'>

        <div className='flex'>
          <h1 className='font-bold text-5xl relative top-5 py-5'>Welcome </h1>

          <HiOutlineArrowNarrowRight className=' relative top-11 left-11 text-5xl' link="/FacultySelect" />

        </div>

        {/* /////////////////// */}
        <div className=' pt-52 '>
          <div>
            <Image src="/trinitylogo.png" width={500} height={500} alt='logo' />
          </div>
        </div>



        <Link href="/Signup" className='flex justify-center relative top-60'>
          <button type="submit" className=" border-none bg-customBlue w-4/5 py-5 rounded-lg text-white text-lg ">
            Continue
          </button>
        </Link>





















      </main>
    </>
  )
}
